name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2016]
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        if: matrix.os == 'ubuntu-18.04'
        run: |
          sudo apt-get update && sudo apt-get install golang-1.13

      - name: Download Go Modules
        run: |
          go mod download

      - name: Build Package
        if: matrix.os == 'windows-2016'
        run: |
          go build

      - name: Make AppImage
        if: matrix.os == 'ubuntu-18.04'
        run: |
          chmod +x build.sh && bash build.sh

      - name: Upload Assets
        if: matrix.os == 'ubuntu-18.04'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rime-plum-go-x86_64.AppImage
          asset_name: rime-plum-go-$tag.Linux.x86_64.AppImage
          tag: ${{ github.ref }}
          overwrite: true

      - name: Upload Executable
        if: matrix.os == 'windows-2016'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: rime-plum-go.exe
          asset_name: rime-plum-go-$tag.windows.exe
          tag: ${{ github.ref }}
          overwrite: true
